name: Auto Review

on:
  pull_request_target:
    types:
    - ready_for_review
    - converted_to_draft

jobs:
  start-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pre setup 1
        run: |
          echo "$SCRIPT" > tmp/prepare.js
          node tmp/prepare.js
        env:
          SCRIPT: |
            let ref = process.env.GITHUB_REF;
            ref = 'origin/' + ref.substring(ref.lastIndexOf('/') + 1);
            let cmd = require('child_process').execSync('git rev-parse ' + ref).toString('utf-8');
            require('fs').writeSync('tmp/rcrf', cmd.trim());
      - name: Pre setup
        run: |
          BASE=$(cat tmp/rcrf)
          echo $BASE

          git checkout "$BASE" -- tmp
          git --no-pager diff "$BASE..$GITHUB_SHA" --no-color --output tmp/change-diff
          git --no-pager diff "$BASE..$GITHUB_SHA" --name-only --output tmp/name-changed

          git checkout "$GITHUB_SHA" -- .script
          git checkout "$GITHUB_SHA" -- protected
      - run: cat .script/check-pr.js
      - run: node .script/check-pr.js
        env:
          GH_TOKEN: ${{ github.token }}
          ACTOR: ${{ github.event.pull_request.user.login }}
          PR_NUM: ${{ github.event.pull_request.number }}
          REPO_N: ${{ github.event.repository.full_name }}

