name: Auto Review

on:
  pull_request_target:
    types:
      - ready_for_review
      - converted_to_draft

jobs:
  start-review:
    runs-on: ubuntu-latest
    env:
      PR_NUM: ${{ github.event.pull_request.number }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      # It checkout the origin repository not pull request. Very safe
      - uses: actions/checkout@v2
      - name: Pre setup
        run: |
          git fetch origin pull/$PR_NUM/head:THE_PR
          echo $BASE_SHA

          git --no-pager diff "$THE_PR..$BASE_SHA" --no-color --output tmp/change-diff
          git --no-pager diff "$THE_PR..$BASE_SHA" --name-only --output tmp/name-changed

      - run: node .script/check-pr.js
        env:
          GH_TOKEN: ${{ github.token }}
          ACTOR: ${{ github.event.pull_request.user.login }}
          REPO_N: ${{ github.event.repository.full_name }}

